name: Lint Code Base

on: [push, pull_request]

jobs:
  codestyle-php:
    name: PHP codestyle checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Code Style
        run: php vendor/bin/phpcs --standard=ci/phpcs.xml .

  compatibility-php:
    name: PHP Code Compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Compatibility
        run: php vendor/bin/phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.0-8.4 --ignore=vendor/* .

