name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on tag push like v1.0.0

jobs:
  codestyle-php:
    name: PHP codestyle checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Code Style
        run: php vendor/bin/phpcs --standard=ci/phpcs.xml .

  compatibility-php:
    name: PHP Code Compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: php ci/composer.phar install

      - name: Check PHP Compatibility
        run: php vendor/bin/phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.0-8.4 --ignore=vendor/* .

  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can access tags and branches
          ref: ${{ github.ref }}

      - name: Run build script
        run: bash _tools/build_release.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}  # Use the PAT instead of the default GITHUB_TOKEN
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release for ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}  # Use the PAT instead of the default GITHUB_TOKEN
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./social-elements-for-wpbakery.zip
          asset_name: release-${{ github.ref_name }}.zip
          asset_content_type: application/zip
